### PR TITLE
Fix Now Build, (Update react-spring version, types)

### PR DESCRIPTION
**Pull request by azizhk**
This should have been an issue but thought better to get it fixed in a PR.

### CODE REVIEW

**Comment by ritz078** [comment]
is something with failed build already merged in master?

**Comment by azizhk** [comment]
At the time of the merge, I don't think it was failing. Hence I think pebble.now.sh is currently up.

**Comment by azizhk** [comment]
Check once on your local machine if you are getting the error.

**Comment by azizhk** [comment]
I got the error on my local.
```sh
rm -rf ./node_modules
npm install
npm run storybook
```
Seems like react-spring's types have something going on.

**Comment by azizhk** [comment]
But still does not fix the issue that now deployments uses npm instead of yarn.
So sometimes we will have to fix such issues again and again.

**Pull request merged**
